title: 吳老師音樂工作室
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

# topnav_title: ELIXIR toolkit theme
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "吳老師音樂工作室 成人班 - 新手上路."
# Metadata description of the website

dsw_deep_link_prefix:
# prefix for DSW deep links to a certain question

gtag:
# Google analytics tag

matomo:
# Matomo domain where Matomo is running

plausible: 
# Plausible tag
plausible_src: 
# default: 'https://plausible.io/js/plausible.js

exclude:
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick

theme_variables: 
  # git_host: GitHub
  # back_to_top: true
  # privacy_statement_url: /privacy
  # github_buttons: 
  #   position: top
  #   edit_me: true
  #   open_issue: true
  #   history: true
  # toc:
  #   full_width: false
  #   min_headers: 2
  #   headers: 'h2'
   topnav:
     theme: light
     #brand_logo: assets/img/main_logo.svg
     brand_logo: assets/img/music-Logo.png
     github: false
     twitter: false
  # theme_color: 0d6efd
  # fonts:
  #   - url towards a font

# --- Missing in gitlab: ---
# github:
#   repository_url: https://github.com/wenrongwu/wenrongwu.github.io
#   source:
#     branch: main


repository: wenrongwu/wenrongwu.github.io
remote_theme: ELIXIR-Belgium/elixir-toolkit-theme